# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preferences.ui'
#
# Created: Tue Jun 19 18:48:16 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Preferences(object):
    def setupUi(self, Preferences):
        Preferences.setObjectName(_fromUtf8("Preferences"))
        Preferences.resize(400, 300)
        self.verticalLayout = QtGui.QVBoxLayout(Preferences)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(Preferences)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Bibliotheque = QtGui.QWidget()
        self.Bibliotheque.setObjectName(_fromUtf8("Bibliotheque"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Bibliotheque)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.Bibliotheque)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditPathLib = QtGui.QLineEdit(self.Bibliotheque)
        self.lineEditPathLib.setObjectName(_fromUtf8("lineEditPathLib"))
        self.horizontalLayout.addWidget(self.lineEditPathLib)
        self.pushButtonChangeLib = QtGui.QPushButton(self.Bibliotheque)
        self.pushButtonChangeLib.setObjectName(_fromUtf8("pushButtonChangeLib"))
        self.horizontalLayout.addWidget(self.pushButtonChangeLib)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.Bibliotheque, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.spinBoxBoilOff = QtGui.QSpinBox(self.tab)
        self.spinBoxBoilOff.setObjectName(_fromUtf8("spinBoxBoilOff"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBoxBoilOff)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.spinBoxCooling = QtGui.QSpinBox(self.tab)
        self.spinBoxCooling.setObjectName(_fromUtf8("spinBoxCooling"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxCooling)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.spinBoxGrainTemp = QtGui.QSpinBox(self.tab)
        self.spinBoxGrainTemp.setObjectName(_fromUtf8("spinBoxGrainTemp"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBoxGrainTemp)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.doubleSpinBoxFudgeFactor = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxFudgeFactor.setObjectName(_fromUtf8("doubleSpinBoxFudgeFactor"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxFudgeFactor)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_6)
        self.doubleSpinBoxGrainRetention = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxGrainRetention.setObjectName(_fromUtf8("doubleSpinBoxGrainRetention"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxGrainRetention)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.Apparence = QtGui.QWidget()
        self.Apparence.setObjectName(_fromUtf8("Apparence"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Apparence)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.Apparence)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButtonMenuBar = QtGui.QRadioButton(self.groupBox)
        self.radioButtonMenuBar.setChecked(True)
        self.radioButtonMenuBar.setObjectName(_fromUtf8("radioButtonMenuBar"))
        self.horizontalLayout_2.addWidget(self.radioButtonMenuBar)
        self.radioButtonMenuButton = QtGui.QRadioButton(self.groupBox)
        self.radioButtonMenuButton.setChecked(False)
        self.radioButtonMenuButton.setObjectName(_fromUtf8("radioButtonMenuButton"))
        self.horizontalLayout_2.addWidget(self.radioButtonMenuButton)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Apparence, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Preferences)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Preferences)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Preferences.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Preferences.reject)
        QtCore.QMetaObject.connectSlotsByName(Preferences)

    def retranslateUi(self, Preferences):
        Preferences.setWindowTitle(QtGui.QApplication.translate("Preferences", "Préférences", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Preferences", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Emplacement de la bibliothèque : </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChangeLib.setText(QtGui.QApplication.translate("Preferences", "Changer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Bibliotheque), QtGui.QApplication.translate("Preferences", "Bibliothèque", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Preferences", "Taux d\'évaporation (%/h) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Preferences", "Pertes par refroidissement (%) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Preferences", "Température du grain :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Preferences", "Facteur de correction des températures :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Preferences", "Rétention d\'eau par le grain (l/kg) :", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Preferences", "Brassage", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Preferences", "Menus", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonMenuBar.setText(QtGui.QApplication.translate("Preferences", "Barre de menus", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonMenuButton.setText(QtGui.QApplication.translate("Preferences", "Bouton unique", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Apparence), QtGui.QApplication.translate("Preferences", "Apparence", None, QtGui.QApplication.UnicodeUTF8))

