# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reader.ui'
#
# Created: Thu Jun  7 20:12:38 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1293, 715)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Images/bulle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setLineWidth(1)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.gridLayout = QtGui.QGridLayout(self.page)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.widgetEditeur = QtGui.QWidget(self.page)
        self.widgetEditeur.setObjectName(_fromUtf8("widgetEditeur"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widgetEditeur)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.checkBoxIng = QtGui.QCheckBox(self.widgetEditeur)
        self.checkBoxIng.setObjectName(_fromUtf8("checkBoxIng"))
        self.horizontalLayout_5.addWidget(self.checkBoxIng)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.pushButtonChangeIngredients = QtGui.QPushButton(self.widgetEditeur)
        self.pushButtonChangeIngredients.setCheckable(True)
        self.pushButtonChangeIngredients.setObjectName(_fromUtf8("pushButtonChangeIngredients"))
        self.horizontalLayout_5.addWidget(self.pushButtonChangeIngredients)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 3, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_7.addLayout(self.gridLayout_6, 4, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboBoxMashProfiles = QtGui.QComboBox(self.widgetEditeur)
        self.comboBoxMashProfiles.setMinimumSize(QtCore.QSize(400, 0))
        self.comboBoxMashProfiles.setObjectName(_fromUtf8("comboBoxMashProfiles"))
        self.horizontalLayout_3.addWidget(self.comboBoxMashProfiles)
        self.pushButtonMashDetails = QtGui.QPushButton(self.widgetEditeur)
        self.pushButtonMashDetails.setObjectName(_fromUtf8("pushButtonMashDetails"))
        self.horizontalLayout_3.addWidget(self.pushButtonMashDetails)
        self.pushButtonBrewdayMode = QtGui.QPushButton(self.widgetEditeur)
        self.pushButtonBrewdayMode.setObjectName(_fromUtf8("pushButtonBrewdayMode"))
        self.horizontalLayout_3.addWidget(self.pushButtonBrewdayMode)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout_7.addLayout(self.horizontalLayout_3, 7, 0, 1, 1)
        self.widgetIngredients = QtGui.QWidget(self.widgetEditeur)
        self.widgetIngredients.setObjectName(_fromUtf8("widgetIngredients"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.widgetIngredients)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.comboBox = QtGui.QComboBox(self.widgetIngredients)
        self.comboBox.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBox.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_10.addWidget(self.comboBox)
        self.pushButtonAjouter_2 = QtGui.QPushButton(self.widgetIngredients)
        self.pushButtonAjouter_2.setObjectName(_fromUtf8("pushButtonAjouter_2"))
        self.horizontalLayout_10.addWidget(self.pushButtonAjouter_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.comboBoxH = QtGui.QComboBox(self.widgetIngredients)
        self.comboBoxH.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBoxH.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBoxH.setObjectName(_fromUtf8("comboBoxH"))
        self.horizontalLayout_11.addWidget(self.comboBoxH)
        self.pushButtonAjouterH = QtGui.QPushButton(self.widgetIngredients)
        self.pushButtonAjouterH.setObjectName(_fromUtf8("pushButtonAjouterH"))
        self.horizontalLayout_11.addWidget(self.pushButtonAjouterH)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.comboBoxM = QtGui.QComboBox(self.widgetIngredients)
        self.comboBoxM.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBoxM.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBoxM.setObjectName(_fromUtf8("comboBoxM"))
        self.horizontalLayout_12.addWidget(self.comboBoxM)
        self.pushButtonAjouterM = QtGui.QPushButton(self.widgetIngredients)
        self.pushButtonAjouterM.setObjectName(_fromUtf8("pushButtonAjouterM"))
        self.horizontalLayout_12.addWidget(self.pushButtonAjouterM)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.comboBoxY = QtGui.QComboBox(self.widgetIngredients)
        self.comboBoxY.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBoxY.setMaximumSize(QtCore.QSize(170, 16777215))
        self.comboBoxY.setObjectName(_fromUtf8("comboBoxY"))
        self.horizontalLayout_13.addWidget(self.comboBoxY)
        self.pushButtonAjouterY = QtGui.QPushButton(self.widgetIngredients)
        self.pushButtonAjouterY.setObjectName(_fromUtf8("pushButtonAjouterY"))
        self.horizontalLayout_13.addWidget(self.pushButtonAjouterY)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pushButtonEnlever = QtGui.QPushButton(self.widgetIngredients)
        self.pushButtonEnlever.setObjectName(_fromUtf8("pushButtonEnlever"))
        self.horizontalLayout_7.addWidget(self.pushButtonEnlever)
        self.gridLayout_7.addWidget(self.widgetIngredients, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.labelRecette = QtGui.QLabel(self.widgetEditeur)
        self.labelRecette.setObjectName(_fromUtf8("labelRecette"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelRecette)
        self.lineEditRecette = QtGui.QLineEdit(self.widgetEditeur)
        self.lineEditRecette.setObjectName(_fromUtf8("lineEditRecette"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditRecette)
        self.labelGenre = QtGui.QLabel(self.widgetEditeur)
        self.labelGenre.setObjectName(_fromUtf8("labelGenre"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelGenre)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEditGenre = QtGui.QLineEdit(self.widgetEditeur)
        self.lineEditGenre.setObjectName(_fromUtf8("lineEditGenre"))
        self.horizontalLayout.addWidget(self.lineEditGenre)
        self.pushButtonChangerStyle = QtGui.QPushButton(self.widgetEditeur)
        self.pushButtonChangerStyle.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("Images/document-properties.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonChangerStyle.setIcon(icon1)
        self.pushButtonChangerStyle.setCheckable(True)
        self.pushButtonChangerStyle.setObjectName(_fromUtf8("pushButtonChangerStyle"))
        self.horizontalLayout.addWidget(self.pushButtonChangerStyle)
        self.comboBoxStyle = QtGui.QComboBox(self.widgetEditeur)
        self.comboBoxStyle.setObjectName(_fromUtf8("comboBoxStyle"))
        self.horizontalLayout.addWidget(self.comboBoxStyle)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setContentsMargins(20, -1, -1, -1)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_3 = QtGui.QLabel(self.widgetEditeur)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditBrewer = QtGui.QLineEdit(self.widgetEditeur)
        self.lineEditBrewer.setObjectName(_fromUtf8("lineEditBrewer"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditBrewer)
        self.label_4 = QtGui.QLabel(self.widgetEditeur)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.comboBoxType = QtGui.QComboBox(self.widgetEditeur)
        self.comboBoxType.setObjectName(_fromUtf8("comboBoxType"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.comboBoxType)
        self.horizontalLayout_2.addLayout(self.formLayout_3)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_7.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.labelFermentables = QtGui.QLabel(self.widgetEditeur)
        self.labelFermentables.setObjectName(_fromUtf8("labelFermentables"))
        self.gridLayout_7.addWidget(self.labelFermentables, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tableViewF = QtGui.QTableView(self.widgetEditeur)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableViewF.sizePolicy().hasHeightForWidth())
        self.tableViewF.setSizePolicy(sizePolicy)
        self.tableViewF.setEditTriggers(QtGui.QAbstractItemView.AllEditTriggers)
        self.tableViewF.setAlternatingRowColors(True)
        self.tableViewF.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableViewF.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableViewF.setShowGrid(False)
        self.tableViewF.setGridStyle(QtCore.Qt.NoPen)
        self.tableViewF.setObjectName(_fromUtf8("tableViewF"))
        self.tableViewF.horizontalHeader().setCascadingSectionResizes(True)
        self.tableViewF.horizontalHeader().setDefaultSectionSize(175)
        self.tableViewF.horizontalHeader().setStretchLastSection(True)
        self.tableViewF.verticalHeader().setVisible(False)
        self.tableViewF.verticalHeader().setDefaultSectionSize(22)
        self.tableViewF.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_4.addWidget(self.tableViewF)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.widgetEditeur)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_7.addWidget(self.label_8, 6, 0, 1, 1)
        self.gridLayout.addWidget(self.widgetEditeur, 1, 0, 1, 1)
        self.widgetProfile = QtGui.QWidget(self.page)
        self.widgetProfile.setStyleSheet(_fromUtf8(""))
        self.widgetProfile.setObjectName(_fromUtf8("widgetProfile"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.widgetProfile)
        self.verticalLayout_6.setContentsMargins(30, -1, -1, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_7 = QtGui.QLabel(self.widgetProfile)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_4.addWidget(self.label_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.labelRendement = QtGui.QLabel(self.widgetProfile)
        self.labelRendement.setObjectName(_fromUtf8("labelRendement"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelRendement)
        self.doubleSpinBoxRendemt = QtGui.QDoubleSpinBox(self.widgetProfile)
        self.doubleSpinBoxRendemt.setObjectName(_fromUtf8("doubleSpinBoxRendemt"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxRendemt)
        self.labelBoil = QtGui.QLabel(self.widgetProfile)
        self.labelBoil.setObjectName(_fromUtf8("labelBoil"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelBoil)
        self.spinBoxBoil = QtGui.QSpinBox(self.widgetProfile)
        self.spinBoxBoil.setMaximum(999)
        self.spinBoxBoil.setSingleStep(10)
        self.spinBoxBoil.setObjectName(_fromUtf8("spinBoxBoil"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBoxBoil)
        self.label_2Volume = QtGui.QLabel(self.widgetProfile)
        self.label_2Volume.setObjectName(_fromUtf8("label_2Volume"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2Volume)
        self.doubleSpinBox_2Volume = QtGui.QDoubleSpinBox(self.widgetProfile)
        self.doubleSpinBox_2Volume.setObjectName(_fromUtf8("doubleSpinBox_2Volume"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_2Volume)
        self.pushButtonVolMore = QtGui.QPushButton(self.widgetProfile)
        self.pushButtonVolMore.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("Images/more.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVolMore.setIcon(icon2)
        self.pushButtonVolMore.setCheckable(True)
        self.pushButtonVolMore.setObjectName(_fromUtf8("pushButtonVolMore"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.pushButtonVolMore)
        self.verticalLayout_6.addLayout(self.formLayout_4)
        self.widgetVol = QtGui.QWidget(self.widgetProfile)
        self.widgetVol.setObjectName(_fromUtf8("widgetVol"))
        self.formLayout_5 = QtGui.QFormLayout(self.widgetVol)
        self.formLayout_5.setMargin(0)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label = QtGui.QLabel(self.widgetVol)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.doubleSpinBoxVolPre = QtGui.QDoubleSpinBox(self.widgetVol)
        self.doubleSpinBoxVolPre.setMaximum(999.0)
        self.doubleSpinBoxVolPre.setSingleStep(10.0)
        self.doubleSpinBoxVolPre.setObjectName(_fromUtf8("doubleSpinBoxVolPre"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBoxVolPre)
        self.labelSG = QtGui.QLabel(self.widgetVol)
        self.labelSG.setObjectName(_fromUtf8("labelSG"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelSG)
        self.label_2 = QtGui.QLabel(self.widgetVol)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_6.addWidget(self.widgetVol)
        self.pushButtonRecipeNotes = QtGui.QPushButton(self.widgetProfile)
        self.pushButtonRecipeNotes.setObjectName(_fromUtf8("pushButtonRecipeNotes"))
        self.verticalLayout_6.addWidget(self.pushButtonRecipeNotes)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 35, -1, 10)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_6 = QtGui.QLabel(self.widgetProfile)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setContentsMargins(-1, 0, -1, 35)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.labelOG = QtGui.QLabel(self.widgetProfile)
        self.labelOG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelOG.setObjectName(_fromUtf8("labelOG"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelOG)
        self.labelOGV = QtGui.QLabel(self.widgetProfile)
        self.labelOGV.setText(_fromUtf8(""))
        self.labelOGV.setObjectName(_fromUtf8("labelOGV"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelOGV)
        self.labelFG = QtGui.QLabel(self.widgetProfile)
        self.labelFG.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFG.setObjectName(_fromUtf8("labelFG"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.labelFG)
        self.labelFGV = QtGui.QLabel(self.widgetProfile)
        self.labelFGV.setText(_fromUtf8(""))
        self.labelFGV.setObjectName(_fromUtf8("labelFGV"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelFGV)
        self.labelEBC = QtGui.QLabel(self.widgetProfile)
        self.labelEBC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelEBC.setObjectName(_fromUtf8("labelEBC"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.labelEBC)
        self.labelEBCV = QtGui.QLabel(self.widgetProfile)
        self.labelEBCV.setText(_fromUtf8(""))
        self.labelEBCV.setObjectName(_fromUtf8("labelEBCV"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.labelEBCV)
        self.labelIBU = QtGui.QLabel(self.widgetProfile)
        self.labelIBU.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelIBU.setObjectName(_fromUtf8("labelIBU"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.labelIBU)
        self.labelIBUV = QtGui.QLabel(self.widgetProfile)
        self.labelIBUV.setText(_fromUtf8(""))
        self.labelIBUV.setObjectName(_fromUtf8("labelIBUV"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.labelIBUV)
        self.labelAlc = QtGui.QLabel(self.widgetProfile)
        self.labelAlc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAlc.setObjectName(_fromUtf8("labelAlc"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.labelAlc)
        self.labelAlcv = QtGui.QLabel(self.widgetProfile)
        self.labelAlcv.setText(_fromUtf8(""))
        self.labelAlcv.setObjectName(_fromUtf8("labelAlcv"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.labelAlcv)
        self.verticalLayout_6.addLayout(self.formLayout)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 10)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_5 = QtGui.QLabel(self.widgetProfile)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_7.addWidget(self.label_5)
        self.verticalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widgetColor = QtGui.QWidget(self.widgetProfile)
        self.widgetColor.setMinimumSize(QtCore.QSize(30, 10))
        self.widgetColor.setStyleSheet(_fromUtf8(""))
        self.widgetColor.setObjectName(_fromUtf8("widgetColor"))
        self.verticalLayout.addWidget(self.widgetColor)
        self.verticalLayout_6.addLayout(self.verticalLayout)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.gridLayout.addWidget(self.widgetProfile, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(self.page_2)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.listViewBiblio = QtGui.QListView(self.widget)
        self.listViewBiblio.setStyleSheet(_fromUtf8("background-color: rgb(116, 116, 116);\n"
"color: rgb(255, 255, 255);"))
        self.listViewBiblio.setDragEnabled(True)
        self.listViewBiblio.setDragDropMode(QtGui.QAbstractItemView.InternalMove)
        self.listViewBiblio.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.listViewBiblio.setMovement(QtGui.QListView.Free)
        self.listViewBiblio.setFlow(QtGui.QListView.LeftToRight)
        self.listViewBiblio.setSpacing(30)
        self.listViewBiblio.setViewMode(QtGui.QListView.IconMode)
        self.listViewBiblio.setObjectName(_fromUtf8("listViewBiblio"))
        self.gridLayout_3.addWidget(self.listViewBiblio, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.textEditRecipeNotes = QtGui.QTextEdit(self.page_3)
        self.textEditRecipeNotes.setObjectName(_fromUtf8("textEditRecipeNotes"))
        self.gridLayout_5.addWidget(self.textEditRecipeNotes, 0, 0, 1, 1)
        self.buttonBoxRecipeNotes = QtGui.QDialogButtonBox(self.page_3)
        self.buttonBoxRecipeNotes.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBoxRecipeNotes.setObjectName(_fromUtf8("buttonBoxRecipeNotes"))
        self.gridLayout_5.addWidget(self.buttonBoxRecipeNotes, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_15 = QtGui.QLabel(self.page_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_10.addWidget(self.label_15)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.listWidgetMashProfiles = QtGui.QListWidget(self.page_4)
        self.listWidgetMashProfiles.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetMashProfiles.setProperty("isWrapping", False)
        self.listWidgetMashProfiles.setViewMode(QtGui.QListView.ListMode)
        self.listWidgetMashProfiles.setObjectName(_fromUtf8("listWidgetMashProfiles"))
        self.verticalLayout_8.addWidget(self.listWidgetMashProfiles)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButtonRemoveProfile = QtGui.QPushButton(self.page_4)
        self.pushButtonRemoveProfile.setEnabled(False)
        self.pushButtonRemoveProfile.setObjectName(_fromUtf8("pushButtonRemoveProfile"))
        self.horizontalLayout_9.addWidget(self.pushButtonRemoveProfile)
        self.pushButtonNewProfile = QtGui.QPushButton(self.page_4)
        self.pushButtonNewProfile.setObjectName(_fromUtf8("pushButtonNewProfile"))
        self.horizontalLayout_9.addWidget(self.pushButtonNewProfile)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.widget1 = QtGui.QWidget(self.page_4)
        self.widget1.setMinimumSize(QtCore.QSize(500, 0))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.formLayout_7 = QtGui.QFormLayout(self.widget1)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_7.setContentsMargins(50, -1, 50, -1)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_16 = QtGui.QLabel(self.widget1)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_16)
        self.labelMashName = QtGui.QLabel(self.widget1)
        self.labelMashName.setObjectName(_fromUtf8("labelMashName"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelMashName)
        self.label_17 = QtGui.QLabel(self.widget1)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_17)
        self.labelMashPh = QtGui.QLabel(self.widget1)
        self.labelMashPh.setObjectName(_fromUtf8("labelMashPh"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelMashPh)
        self.label_24 = QtGui.QLabel(self.widget1)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_24)
        self.labelMashSpargeTemp = QtGui.QLabel(self.widget1)
        self.labelMashSpargeTemp.setObjectName(_fromUtf8("labelMashSpargeTemp"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelMashSpargeTemp)
        self.pushButtonMashEdit = QtGui.QPushButton(self.widget1)
        self.pushButtonMashEdit.setEnabled(False)
        self.pushButtonMashEdit.setObjectName(_fromUtf8("pushButtonMashEdit"))
        self.formLayout_7.setWidget(3, QtGui.QFormLayout.LabelRole, self.pushButtonMashEdit)
        self.horizontalLayout_14.addWidget(self.widget1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem7)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_14 = QtGui.QLabel(self.page_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_9.addWidget(self.label_14)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listWidgetSteps = QtGui.QListWidget(self.page_4)
        self.listWidgetSteps.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidgetSteps.setObjectName(_fromUtf8("listWidgetSteps"))
        self.verticalLayout_2.addWidget(self.listWidgetSteps)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.pushButtonStepRemove = QtGui.QPushButton(self.page_4)
        self.pushButtonStepRemove.setEnabled(False)
        self.pushButtonStepRemove.setObjectName(_fromUtf8("pushButtonStepRemove"))
        self.horizontalLayout_6.addWidget(self.pushButtonStepRemove)
        self.pushButtonNewStep = QtGui.QPushButton(self.page_4)
        self.pushButtonNewStep.setObjectName(_fromUtf8("pushButtonNewStep"))
        self.horizontalLayout_6.addWidget(self.pushButtonNewStep)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.widget2 = QtGui.QWidget(self.page_4)
        self.widget2.setMinimumSize(QtCore.QSize(500, 0))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.formLayout_6 = QtGui.QFormLayout(self.widget2)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setContentsMargins(50, -1, 50, -1)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_9 = QtGui.QLabel(self.widget2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.labelStepName = QtGui.QLabel(self.widget2)
        self.labelStepName.setObjectName(_fromUtf8("labelStepName"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelStepName)
        self.label_10 = QtGui.QLabel(self.widget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_10)
        self.labelStepType = QtGui.QLabel(self.widget2)
        self.labelStepType.setObjectName(_fromUtf8("labelStepType"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelStepType)
        self.label_11 = QtGui.QLabel(self.widget2)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_11)
        self.labelStepTime = QtGui.QLabel(self.widget2)
        self.labelStepTime.setObjectName(_fromUtf8("labelStepTime"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelStepTime)
        self.label_12 = QtGui.QLabel(self.widget2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_12)
        self.labelStepTemp = QtGui.QLabel(self.widget2)
        self.labelStepTemp.setObjectName(_fromUtf8("labelStepTemp"))
        self.formLayout_6.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelStepTemp)
        self.pushButtonStepEdit = QtGui.QPushButton(self.widget2)
        self.pushButtonStepEdit.setEnabled(False)
        self.pushButtonStepEdit.setObjectName(_fromUtf8("pushButtonStepEdit"))
        self.formLayout_6.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButtonStepEdit)
        self.horizontalLayout_8.addWidget(self.widget2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.verticalLayout_11.addLayout(self.verticalLayout_9)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.buttonBoxMashDetails = QtGui.QDialogButtonBox(self.page_4)
        self.buttonBoxMashDetails.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBoxMashDetails.setObjectName(_fromUtf8("buttonBoxMashDetails"))
        self.horizontalLayout_15.addWidget(self.buttonBoxMashDetails)
        self.pushButtonSaveProfile = QtGui.QPushButton(self.page_4)
        self.pushButtonSaveProfile.setObjectName(_fromUtf8("pushButtonSaveProfile"))
        self.horizontalLayout_15.addWidget(self.pushButtonSaveProfile)
        self.verticalLayout_11.addLayout(self.horizontalLayout_15)
        self.gridLayout_8.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_12 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem9, 2, 0, 1, 1)
        self.label_23 = QtGui.QLabel(self.page_5)
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_12.addWidget(self.label_23, 1, 1, 1, 1)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.groupBox_2 = QtGui.QGroupBox(self.page_5)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.formLayoutSparge = QtGui.QFormLayout()
        self.formLayoutSparge.setObjectName(_fromUtf8("formLayoutSparge"))
        self.labelSparge1 = QtGui.QLabel(self.groupBox_2)
        self.labelSparge1.setObjectName(_fromUtf8("labelSparge1"))
        self.formLayoutSparge.setWidget(0, QtGui.QFormLayout.LabelRole, self.labelSparge1)
        self.labelSparge2 = QtGui.QLabel(self.groupBox_2)
        self.labelSparge2.setObjectName(_fromUtf8("labelSparge2"))
        self.formLayoutSparge.setWidget(1, QtGui.QFormLayout.LabelRole, self.labelSparge2)
        self.labelSpargeVol = QtGui.QLabel(self.groupBox_2)
        self.labelSpargeVol.setObjectName(_fromUtf8("labelSpargeVol"))
        self.formLayoutSparge.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelSpargeVol)
        self.labelSpargeTemp = QtGui.QLabel(self.groupBox_2)
        self.labelSpargeTemp.setObjectName(_fromUtf8("labelSpargeTemp"))
        self.formLayoutSparge.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelSpargeTemp)
        self.labelNoSparge = QtGui.QLabel(self.groupBox_2)
        self.labelNoSparge.setMinimumSize(QtCore.QSize(100, 0))
        self.labelNoSparge.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 196);"))
        self.labelNoSparge.setObjectName(_fromUtf8("labelNoSparge"))
        self.formLayoutSparge.setWidget(2, QtGui.QFormLayout.LabelRole, self.labelNoSparge)
        self.gridLayout_10.addLayout(self.formLayoutSparge, 0, 0, 1, 1)
        self.horizontalLayout_18.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.page_5)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.formLayout_8 = QtGui.QFormLayout()
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_18 = QtGui.QLabel(self.groupBox)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.groupBox)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_19)
        self.labelPreBoilGravity = QtGui.QLabel(self.groupBox)
        self.labelPreBoilGravity.setObjectName(_fromUtf8("labelPreBoilGravity"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelPreBoilGravity)
        self.labelPreBoilVol = QtGui.QLabel(self.groupBox)
        self.labelPreBoilVol.setText(_fromUtf8(""))
        self.labelPreBoilVol.setObjectName(_fromUtf8("labelPreBoilVol"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelPreBoilVol)
        self.gridLayout_9.addLayout(self.formLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_18.addWidget(self.groupBox)
        self.gridLayout_12.addLayout(self.horizontalLayout_18, 3, 0, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_13 = QtGui.QLabel(self.page_5)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_12.addWidget(self.label_13)
        self.tableWidgetStepsBrewday = QtGui.QTableWidget(self.page_5)
        self.tableWidgetStepsBrewday.setMaximumSize(QtCore.QSize(123456, 200))
        self.tableWidgetStepsBrewday.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)
        self.tableWidgetStepsBrewday.setAlternatingRowColors(True)
        self.tableWidgetStepsBrewday.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidgetStepsBrewday.setShowGrid(False)
        self.tableWidgetStepsBrewday.setRowCount(0)
        self.tableWidgetStepsBrewday.setColumnCount(5)
        self.tableWidgetStepsBrewday.setObjectName(_fromUtf8("tableWidgetStepsBrewday"))
        item = QtGui.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetStepsBrewday.setHorizontalHeaderItem(4, item)
        self.tableWidgetStepsBrewday.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidgetStepsBrewday.horizontalHeader().setDefaultSectionSize(175)
        self.tableWidgetStepsBrewday.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetStepsBrewday.verticalHeader().setVisible(False)
        self.tableWidgetStepsBrewday.verticalHeader().setDefaultSectionSize(22)
        self.tableWidgetStepsBrewday.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_12.addWidget(self.tableWidgetStepsBrewday)
        self.labelWarningBiab = QtGui.QLabel(self.page_5)
        self.labelWarningBiab.setMinimumSize(QtCore.QSize(0, 20))
        self.labelWarningBiab.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 196);"))
        self.labelWarningBiab.setObjectName(_fromUtf8("labelWarningBiab"))
        self.verticalLayout_12.addWidget(self.labelWarningBiab)
        self.labelNoDecoction = QtGui.QLabel(self.page_5)
        self.labelNoDecoction.setMinimumSize(QtCore.QSize(0, 20))
        self.labelNoDecoction.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 196);"))
        self.labelNoDecoction.setObjectName(_fromUtf8("labelNoDecoction"))
        self.verticalLayout_12.addWidget(self.labelNoDecoction)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.pushButtonAdjustStep = QtGui.QPushButton(self.page_5)
        self.pushButtonAdjustStep.setObjectName(_fromUtf8("pushButtonAdjustStep"))
        self.horizontalLayout_16.addWidget(self.pushButtonAdjustStep)
        self.verticalLayout_12.addLayout(self.horizontalLayout_16)
        self.gridLayout_12.addLayout(self.verticalLayout_12, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.page_5)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setContentsMargins(-1, 9, -1, 9)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(6)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.radioButtonClassicBrew = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonClassicBrew.setChecked(True)
        self.radioButtonClassicBrew.setObjectName(_fromUtf8("radioButtonClassicBrew"))
        self.horizontalLayout_17.addWidget(self.radioButtonClassicBrew)
        self.radioButtonBIAB = QtGui.QRadioButton(self.groupBox_3)
        self.radioButtonBIAB.setObjectName(_fromUtf8("radioButtonBIAB"))
        self.horizontalLayout_17.addWidget(self.radioButtonBIAB)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.gridLayout_11.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem12, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.groupBox_3, 0, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem13, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1293, 23))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFichier = QtGui.QMenu(self.menuBar)
        self.menuFichier.setObjectName(_fromUtf8("menuFichier"))
        self.menuEdition = QtGui.QMenu(self.menuBar)
        self.menuEdition.setObjectName(_fromUtf8("menuEdition"))
        self.menuOutils = QtGui.QMenu(self.menuBar)
        self.menuOutils.setObjectName(_fromUtf8("menuOutils"))
        self.menuVue = QtGui.QMenu(self.menuBar)
        self.menuVue.setObjectName(_fromUtf8("menuVue"))
        self.menuAide = QtGui.QMenu(self.menuBar)
        self.menuAide.setObjectName(_fromUtf8("menuAide"))
        self.menuToto = QtGui.QMenu(self.menuBar)
        self.menuToto.setObjectName(_fromUtf8("menuToto"))
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setMovable(False)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionOuvrir = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Images/document-open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOuvrir.setIcon(icon3)
        self.actionOuvrir.setObjectName(_fromUtf8("actionOuvrir"))
        self.actionQuitter = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("Images/application-exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuitter.setIcon(icon4)
        self.actionQuitter.setObjectName(_fromUtf8("actionQuitter"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Images/help-about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionEnregistrer = QtGui.QAction(MainWindow)
        self.actionEnregistrer.setObjectName(_fromUtf8("actionEnregistrer"))
        self.actionEnregistrer_Sous = QtGui.QAction(MainWindow)
        self.actionEnregistrer_Sous.setObjectName(_fromUtf8("actionEnregistrer_Sous"))
        self.actionQuitter_2 = QtGui.QAction(MainWindow)
        self.actionQuitter_2.setObjectName(_fromUtf8("actionQuitter_2"))
        self.actionOuvrir_2 = QtGui.QAction(MainWindow)
        self.actionOuvrir_2.setObjectName(_fromUtf8("actionOuvrir_2"))
        self.actionEditGrains = QtGui.QAction(MainWindow)
        self.actionEditGrains.setObjectName(_fromUtf8("actionEditGrains"))
        self.actionEditHoublons = QtGui.QAction(MainWindow)
        self.actionEditHoublons.setObjectName(_fromUtf8("actionEditHoublons"))
        self.actionEditDivers = QtGui.QAction(MainWindow)
        self.actionEditDivers.setObjectName(_fromUtf8("actionEditDivers"))
        self.actionEditLevures = QtGui.QAction(MainWindow)
        self.actionEditLevures.setObjectName(_fromUtf8("actionEditLevures"))
        self.actionNouvelle_recette = QtGui.QAction(MainWindow)
        self.actionNouvelle_recette.setIcon(icon2)
        self.actionNouvelle_recette.setObjectName(_fromUtf8("actionNouvelle_recette"))
        self.actionCorrectionDens = QtGui.QAction(MainWindow)
        self.actionCorrectionDens.setObjectName(_fromUtf8("actionCorrectionDens"))
        self.actionCalculAlc = QtGui.QAction(MainWindow)
        self.actionCalculAlc.setObjectName(_fromUtf8("actionCalculAlc"))
        self.actionImprimer = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("Images/print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImprimer.setIcon(icon6)
        self.actionImprimer.setObjectName(_fromUtf8("actionImprimer"))
        self.actionDilution = QtGui.QAction(MainWindow)
        self.actionDilution.setObjectName(_fromUtf8("actionDilution"))
        self.actionEvaporation = QtGui.QAction(MainWindow)
        self.actionEvaporation.setObjectName(_fromUtf8("actionEvaporation"))
        self.actionExporterHtml = QtGui.QAction(MainWindow)
        self.actionExporterHtml.setObjectName(_fromUtf8("actionExporterHtml"))
        self.actionPaliers = QtGui.QAction(MainWindow)
        self.actionPaliers.setObjectName(_fromUtf8("actionPaliers"))
        self.actionRestaurerIngredients = QtGui.QAction(MainWindow)
        self.actionRestaurerIngredients.setObjectName(_fromUtf8("actionRestaurerIngredients"))
        self.actionRecharger = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("Images/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecharger.setIcon(icon7)
        self.actionRecharger.setObjectName(_fromUtf8("actionRecharger"))
        self.actionSwitch = QtGui.QAction(MainWindow)
        self.actionSwitch.setObjectName(_fromUtf8("actionSwitch"))
        self.actionVueEditeur = QtGui.QAction(MainWindow)
        self.actionVueEditeur.setObjectName(_fromUtf8("actionVueEditeur"))
        self.actionVueBibliotheque = QtGui.QAction(MainWindow)
        self.actionVueBibliotheque.setObjectName(_fromUtf8("actionVueBibliotheque"))
        self.actionVueEditeurToolBar = QtGui.QAction(MainWindow)
        self.actionVueEditeurToolBar.setCheckable(True)
        self.actionVueEditeurToolBar.setChecked(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("Images/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVueEditeurToolBar.setIcon(icon8)
        self.actionVueEditeurToolBar.setObjectName(_fromUtf8("actionVueEditeurToolBar"))
        self.actionVueBibliothequeToolBar = QtGui.QAction(MainWindow)
        self.actionVueBibliothequeToolBar.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("Images/library.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVueBibliothequeToolBar.setIcon(icon9)
        self.actionVueBibliothequeToolBar.setObjectName(_fromUtf8("actionVueBibliothequeToolBar"))
        self.actionEnregistrerToolBar = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("Images/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnregistrerToolBar.setIcon(icon10)
        self.actionEnregistrerToolBar.setObjectName(_fromUtf8("actionEnregistrerToolBar"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuFichier.addAction(self.actionOuvrir_2)
        self.menuFichier.addAction(self.actionNouvelle_recette)
        self.menuFichier.addAction(self.actionRecharger)
        self.menuFichier.addAction(self.actionImprimer)
        self.menuFichier.addAction(self.actionEnregistrer)
        self.menuFichier.addAction(self.actionEnregistrer_Sous)
        self.menuFichier.addAction(self.actionExporterHtml)
        self.menuFichier.addAction(self.actionQuitter_2)
        self.menuEdition.addAction(self.actionEditGrains)
        self.menuEdition.addAction(self.actionEditHoublons)
        self.menuEdition.addAction(self.actionEditDivers)
        self.menuEdition.addAction(self.actionEditLevures)
        self.menuEdition.addAction(self.actionRestaurerIngredients)
        self.menuEdition.addAction(self.actionPreferences)
        self.menuOutils.addAction(self.actionCorrectionDens)
        self.menuOutils.addAction(self.actionCalculAlc)
        self.menuOutils.addAction(self.actionDilution)
        self.menuOutils.addAction(self.actionEvaporation)
        self.menuOutils.addAction(self.actionPaliers)
        self.menuVue.addAction(self.actionVueEditeur)
        self.menuVue.addAction(self.actionVueBibliotheque)
        self.menuAide.addAction(self.actionAbout)
        self.menuToto.addAction(self.actionRecharger)
        self.menuToto.addSeparator()
        self.menuToto.addAction(self.actionVueBibliothequeToolBar)
        self.menuToto.addAction(self.actionNouvelle_recette)
        self.menuToto.addSeparator()
        self.menuToto.addAction(self.actionEnregistrerToolBar)
        self.menuToto.addAction(self.actionImprimer)
        self.menuBar.addAction(self.menuFichier.menuAction())
        self.menuBar.addAction(self.menuVue.menuAction())
        self.menuBar.addAction(self.menuEdition.menuAction())
        self.menuBar.addAction(self.menuOutils.menuAction())
        self.menuBar.addAction(self.menuAide.menuAction())
        self.menuBar.addAction(self.menuToto.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "JolieBulle", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxIng.setText(QtGui.QApplication.translate("MainWindow", "Ajuster les ingrédients (verrouiller le profil)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChangeIngredients.setText(QtGui.QApplication.translate("MainWindow", "Ajouter/Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMashDetails.setText(QtGui.QApplication.translate("MainWindow", "Détails", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonBrewdayMode.setText(QtGui.QApplication.translate("MainWindow", "Mode Brassage", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAjouter_2.setText(QtGui.QApplication.translate("MainWindow", "Ajouter Grain", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAjouterH.setText(QtGui.QApplication.translate("MainWindow", "Ajouter Houblon", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAjouterM.setText(QtGui.QApplication.translate("MainWindow", "Ajouter Divers", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAjouterY.setText(QtGui.QApplication.translate("MainWindow", "Ajouter Levure", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEnlever.setText(QtGui.QApplication.translate("MainWindow", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRecette.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nom de la recette :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGenre.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Genre :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChangerStyle.setToolTip(QtGui.QApplication.translate("MainWindow", "Liste de styles BJCP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Brasseur :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Type :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFermentables.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Ingredients : </span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Brassage :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">CONTEXTE</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRendement.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Rendement (%)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBoil.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Ebullition (min)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2Volume.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Volume (L)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Volume pré-ébullition</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSG.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Densité  pré-ébullition :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRecipeNotes.setText(QtGui.QApplication.translate("MainWindow", "Notes", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">PROFIL</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOG.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Densité Initiale :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFG.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Densité Finale :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelEBC.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">EBC :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelIBU.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">IBU :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAlc.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Droid Sans\'; font-size:9pt;\">Alc :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:600;\">TEINTE</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Profils de brassage :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRemoveProfile.setText(QtGui.QApplication.translate("MainWindow", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNewProfile.setText(QtGui.QApplication.translate("MainWindow", "Nouveau profil", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Nom :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMashName.setText(QtGui.QApplication.translate("MainWindow", "Aucun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">pH :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMashPh.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Rinçage :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMashSpargeTemp.setText(QtGui.QApplication.translate("MainWindow", "0 °C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMashEdit.setText(QtGui.QApplication.translate("MainWindow", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Paliers :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStepRemove.setText(QtGui.QApplication.translate("MainWindow", "Enlever", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNewStep.setText(QtGui.QApplication.translate("MainWindow", "Nouveau palier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Nom :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStepName.setText(QtGui.QApplication.translate("MainWindow", "Aucun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Type :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStepType.setText(QtGui.QApplication.translate("MainWindow", "Aucun", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Durée :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStepTime.setText(QtGui.QApplication.translate("MainWindow", "0 min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Droid Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Température :</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStepTemp.setText(QtGui.QApplication.translate("MainWindow", "0 °C", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStepEdit.setText(QtGui.QApplication.translate("MainWindow", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSaveProfile.setText(QtGui.QApplication.translate("MainWindow", "Enregistrer les profils", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Rinçage", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSparge1.setText(QtGui.QApplication.translate("MainWindow", "Volume de rinçage :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSparge2.setText(QtGui.QApplication.translate("MainWindow", "Température de rinçage :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSpargeVol.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSpargeTemp.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNoSparge.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\">   Pas de rinçage en BIAB</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Pré-ébullition", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Volume théorique pré-ébullition :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("MainWindow", "Densité pré-ébullition :", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPreBoilGravity.setText(QtGui.QApplication.translate("MainWindow", "1.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Volumes d\'eau</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Palier", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Volume d\'eau", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Température de l\'eau", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Ratio", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tableWidgetStepsBrewday.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Infos", None, QtGui.QApplication.UnicodeUTF8))
        self.labelWarningBiab.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Le profil de brassage que vous utilisez n\'est pas adapté au BIAB. Vous ne devriez utiliser qu\'un seul palier d\'infusion.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNoDecoction.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">JolieBulle ne prend pas encore en charge les décoctions. Pas encore !</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdjustStep.setText(QtGui.QApplication.translate("MainWindow", "Ajuster", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Méthode de brassage", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonClassicBrew.setText(QtGui.QApplication.translate("MainWindow", "Classique", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButtonBIAB.setText(QtGui.QApplication.translate("MainWindow", "Volume complet (BIAB)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFichier.setTitle(QtGui.QApplication.translate("MainWindow", "Fichier", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdition.setTitle(QtGui.QApplication.translate("MainWindow", "Edition", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOutils.setTitle(QtGui.QApplication.translate("MainWindow", "Outils", None, QtGui.QApplication.UnicodeUTF8))
        self.menuVue.setTitle(QtGui.QApplication.translate("MainWindow", "Vue", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAide.setTitle(QtGui.QApplication.translate("MainWindow", "Aide", None, QtGui.QApplication.UnicodeUTF8))
        self.menuToto.setTitle(QtGui.QApplication.translate("MainWindow", "toto", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOuvrir.setText(QtGui.QApplication.translate("MainWindow", "Ouvrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "A propos", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrer.setText(QtGui.QApplication.translate("MainWindow", "&Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrer_Sous.setText(QtGui.QApplication.translate("MainWindow", "Enregistrer &sous", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuitter_2.setText(QtGui.QApplication.translate("MainWindow", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOuvrir_2.setText(QtGui.QApplication.translate("MainWindow", "&Ouvrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditGrains.setText(QtGui.QApplication.translate("MainWindow", "Editer la base de Grains", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditHoublons.setText(QtGui.QApplication.translate("MainWindow", "Editer la base de Houblons", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditDivers.setText(QtGui.QApplication.translate("MainWindow", "Editer la base de Divers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditLevures.setText(QtGui.QApplication.translate("MainWindow", "Editer la base de Levures", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNouvelle_recette.setText(QtGui.QApplication.translate("MainWindow", "Nouvelle recette", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCorrectionDens.setText(QtGui.QApplication.translate("MainWindow", "Correction densimètre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCalculAlc.setText(QtGui.QApplication.translate("MainWindow", "Calcul taux d\'alcool", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImprimer.setText(QtGui.QApplication.translate("MainWindow", "Imprimer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDilution.setText(QtGui.QApplication.translate("MainWindow", "Dilution", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEvaporation.setText(QtGui.QApplication.translate("MainWindow", "Evaporation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExporterHtml.setText(QtGui.QApplication.translate("MainWindow", "Exporter vers html", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaliers.setText(QtGui.QApplication.translate("MainWindow", "Assistant paliers", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRestaurerIngredients.setText(QtGui.QApplication.translate("MainWindow", "Restaurer la base des ingrédients", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRecharger.setText(QtGui.QApplication.translate("MainWindow", "Recharger", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSwitch.setText(QtGui.QApplication.translate("MainWindow", "switch", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVueEditeur.setText(QtGui.QApplication.translate("MainWindow", "Editeur de recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVueBibliotheque.setText(QtGui.QApplication.translate("MainWindow", "Bibliothèque de recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVueBibliotheque.setToolTip(QtGui.QApplication.translate("MainWindow", "Bibiliothèque de recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVueEditeurToolBar.setText(QtGui.QApplication.translate("MainWindow", "Editeur", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVueBibliothequeToolBar.setText(QtGui.QApplication.translate("MainWindow", "Bibiliothèque", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVueBibliothequeToolBar.setToolTip(QtGui.QApplication.translate("MainWindow", "Bibiliothèque de recettes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEnregistrerToolBar.setText(QtGui.QApplication.translate("MainWindow", "&Enregistrer", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreferences.setText(QtGui.QApplication.translate("MainWindow", "Préférences", None, QtGui.QApplication.UnicodeUTF8))

