RECIPE_TYPE_ALL_GRAIN = 0
RECIPE_TYPE_PARTIAL_MASH = 1
RECIPE_TYPE_EXTRACT = 2

HOP_FORM_PELLET = 0
HOP_FORM_LEAF = 1
HOP_FORM_PLUG = 2

MISC_USE_BOIL = 'Boil'
MISC_USE_MASH = 'Mash'
MISC_USE_PRIMARY = 'Primary'
MISC_USE_SECONDARY = 'Secondary'
MISC_USE_BOTTLING = 'Bottling'